config/routes.rb
Rails.application.routes.draw do
  resources :contracts

  resources :contests

   get '/cssslider', to: 'app/front#cssslider', as: :app_cssslider
   get '/atencion', to: 'app/front#atencion', as: :app_atencion
   get '/colocacioninstrumentos', to: 'app/front#colocacioninstrumentos', as: :app_colocacioninstrumentos
   get '/index', to: 'app/front#index', as: :app_index
   get '/estructuracion', to: 'app/front#estructuracion', as: :app_estructuracion
   get '/quienessomos', to: 'app/front#quienessomos', as: :app_quienessomos
   get '/juridica', to: 'app/front#juridica', as: :app_juridica
   get '/emisor', to: 'app/front#emisor', as: :app_emisor
   get '/ventajas', to: 'app/front#ventajas', as: :app_ventajas
   get '/contacto', to: 'app/front#contacto', as: :app_contacto
   get '/colocacion', to: 'app/front#colocacion', as: :app_colocacion
   get '/tarifas', to: 'app/front#tarifas', as: :app_tarifas
   get '/persona', to: 'app/front#persona', as: :app_persona
   get '/marcolegal', to: 'app/front#marcolegal', as: :app_marcolegal
   get '/concurso', to: 'contests#concurso'
   get '/contrataciones', to: 'contracts#contrataciones'
   get '/new', to: 'contests#new'
   get '/contrataciones', to: 'app/front#contrataciones', as: :app_contrataciones
   get '/mercadosecundario', to: 'app/front#mercadosecundario', as: :app_mercadosecundario
   get '/custodia', to: 'app/front#custodia', as: :app_custodia
   get '/estadisticas', to: 'app/front#estadisticas', as: :app_estadisticas
   get '/aplicacion', to: 'app/front#aplicacion', as: :app_aplicacion
   get '/calculadora', to: 'app/front#calculadora', as: :app_calculadora
   get '/admin/chart/un_chart/:id', to: 'admin/charts#un_chart', as: :un_chart
   get '/estadisticas/chart_front/:id', to: 'app/front#chart_front', as: :chart_front
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :charts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :banners do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :indicators do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :customizes do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/install_default', action: 'install_default'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
end

app/models/contest.rb
class Contest < ActiveRecord::Base
	has_attached_file :document
	validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocuments.wordprocessingml.document)}
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
 before_action :set_contest, only: [:show, :edit, :update, :destroy]
 before_action :set_setting, only: [:index, :show, :edit, :update, :destroy, :new, :concurso]
  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
    @contests = @contests.all.order("created_at DESC") 
  end

  def concurso
    @contests = Contest.all
    @contests = @contests.all.order("created_at DESC") 
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'El registro a sido creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'El registro ha sido actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'El registro ha sido borrado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    def set_setting
      @setting = Setting.first
      @render = params[:config]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:titulo, :descripcion, :document)
    end
end

app/views/contests/_form.html.haml
= form_for @contest do |f|
  - if @contest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contest.errors.count, "error")} prohibited this contest from being saved:"
      %ul
        - @contest.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :titulo
    = f.text_field :titulo
  .field
    = f.label :descripcion
    = f.text_area :descripcion
  .field   
    = f.file_field :document
  .actions
    = f.submit 'Save'

app/views/contests/concurso.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bolsa Pública
    %meta{:charset => "utf-8"}/
    %link{:href => "assets/css/materialize.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "assets/css/estilos.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "assets/css/fonts.css", :rel => "stylesheet"}/
  %body
    .col.l12
      .cintillo
        %img{:src => "assets/img/cintillo.jpg"}/
    .navbar-fixed
      %nav
        .nav-wrapper.white
          %a.brand-logo{:href => "/index"}
            %img{:src => "assets/img/logo.png"}/
          %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
            %i.material-icons.grey-text.text-darken-4 menu
          %ul.right.hide-on-med-and-down.botonNav
            %li
              %a.red.white-text{:href => "/contacto"} Contacto
          %ul.right.hide-on-med-and-down.botonNav
            %li
              %a.red.darken-3.white-text{:href => "/estadisticas"} Estadísticas
          %ul.right.hide-on-med-and-down.botonNav
            %li
              %a.red.darken-4.white-text{:href => "/tarifas"} Tarifas
          %ul.right.hide-on-med-and-down.botonNav
            %li
              %a.grey.darken-3.white-text{:href => "/quienessomos"} Quienes Somos
          %ul.right.hide-on-med-and-down.botonNav
            %li
              %a.grey.darken-4.white-text{:href => "/index"} Inicio
          %ul#mobile-demo.side-nav
            %li
              %a{:href => "/index"} Inicio
            %li
              %a{:href => "/quienessomos"} Quienes Somos
            %li
              %a{:href => "/tarifas"} Tarifas
            %li
              %a{:href => "/estadisticas"} Estadísticas
            %li
              %a{:href => "/contacto"} Contacto
    .container.titlelist
      .row
        %h4 Concurso Público para Ingreso de Personal
        - @contests.each do |contest|    
          .col.s12.m10.offset-m1.grey.lighten-2.formtop3      
            %h5.red-text.text-darken-4= contest.titulo
            %p= contest.descripcion
            .waves-effect.waves-light.btn.red.darken-4.linkw.lang= link_to 'Consultar', contest.document.url, target: '_blank'    
    %footer.page-footer
      .container
        .row
          .col.s12.m6
            %h5.white-text Bolsa Pública de Valores Bicentenaria
            %p.grey-text.text-lighten-4
              Av. Francisco de Miranda, Edificio Torre Europa, Nivel C,
              %br/
              Urb. El Rosal, Municipio Chacao, Estado Miranda. Zona Postal 1060.
              %br/
              %b Horario de atención al público:
              De 8:00 a.m. a 4:30 p.m.
              %br/
              %b Teléfono:
              0212-9558800.
            %br/
            %ul.social
              %li
                %h6 Redes Sociales:
                %br/
              %li
                %a.icon-facebook.img-circle{:href => "https://www.facebook.com/Bolsa-Publica-de-Valores-Bicentenaria-470631792952689/?fref=ts", :target => "_blank"}
                %a.icon-twitter.img-circle{:href => "https://twitter.com/Bolsa_Publica", :target => "_blank"}
                %a.icon-instagram.img-circle{:href => "https://www.instagram.com/bolsa_publica/", :target => "_blank"}
          .col.l4.offset-l2.s12
            %h5.white-text Menú
            %ul
              %li
                %a.grey-text.text-lighten-3{:href => "/documents/LCFT.pdf", :target => "blank"} Prevención y Control de Legitimación de Capitales y Financiamiento al Terrorismo
              %li
                %a.grey-text.text-lighten-3{:href => "/atencion"} Oficina de Atención al Ciudadano
              %li
                %a.grey-text.text-lighten-3{:href => "/marcolegal"} Marco Jurídico
              %li
                %a.grey-text.text-lighten-3{:href => "http://www.sunaval.gob.ve/snv/site/glosario_terminos.php"} Glosario de términos
              %li
                %a.grey-text.text-lighten-3{:href => "/concurso"} Concurso Público para Ingreso de Personal
              %li
                %a.grey-text.text-lighten-3{:href => "/contrataciones"} Contrataciones Públicas
              %h5.white-text Enlaces de interés
              %ul
                %li
                  %a.grey-text.text-lighten-3{:href => "http://www.mppef.gob.ve", :target => "blank"} Ministerio del Poder Popular de Economía y Finanzas
                %li
                  %a.grey-text.text-lighten-3{:href => "http://www.sunaval.gob.ve", :target => "blank"} Superintendencia Nacional de Valores  
                %li
                  %a.grey-text.text-lighten-3{:href => "http://www.bcv.org.ve", :target => "blank"} Banco Central de Venezuela                                
      .footer-copyright
        .container
          © 2017 Copyright Bolsa Pública de Valores Bicentenaria / RIF: G-20009677-2
    %script{:src => "assets/js/jquery-3.2.1.min.js", :type => "text/javascript"}
    %script{:src => "assets/js/materialize.min.js", :type => "text/javascript"}
    :javascript
      $( document ).ready(function(){
        $(".button-collapse").sideNav();
      })

      $(document).ready(function(){
        $('.slider').slider();
      });    
     

app/views/contests/edit.html.haml
!!!
%html
  %head    
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bolsa Pública
    %meta{:charset => "utf-8"}/
    %link{:href => "assets/css/materialize.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "assets/css/estilos.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "assets/css/fonts.css", :rel => "stylesheet"}/

%h1 Editing contest

= render 'form'

= link_to 'Show', @contest
\|
= link_to 'Back', contests_path

app/views/contests/index.html.haml
!!!
%html
  %head
    = render 'head'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bolsa Pública
    %meta{:charset => "utf-8"}/
    %link{:href => "assets/css/materialize.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "assets/css/estilos.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "assets/css/fonts.css", :rel => "stylesheet"}/

%h1 Listing contests

%table
  %thead
    %tr
      %th Titulo
      %th Descripcion
      %th
      %th
      %th

  %tbody
    - @contests.each do |contest|
      %tr
        %td= contest.titulo
        %td= contest.descripcion
        %td= link_to 'Consultar', contest.document.url, target: '_blank'
        %td= link_to 'Show', contest
        %td= link_to 'Edit', edit_contest_path(contest)
        %td= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Contest', new_contest_path
= link_to 'Concursos', concurso_path

app/views/contests/new.html.haml
!!!
%html
  %head   
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bolsa Pública
    %meta{:charset => "utf-8"}/       
    %link{:href => "assets/css/fonts.css", :rel => "stylesheet"}/    
%body{:bgcolor => "#eeeeee"}
  %nav
    .nav-wrapper.red.darken-4.navtop
      %a.brand-logo{:href => "#"} Concurso Público para Ingreso de Personal
  .container.titlelist
    .row
      %h3 Crear Nuevo

= render 'form'

app/views/contests/show.html.haml
!!!
%html
  %head
    = render 'head'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bolsa Pública
    %meta{:charset => "utf-8"}/
    %link{:href => "assets/css/materialize.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "assets/css/estilos.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "assets/css/fonts.css", :rel => "stylesheet"}/

%p#notice= notice

%p
  %b Titulo:
  = @contest.titulo
%p
  %b Descripcion:
  = @contest.descripcion

= link_to 'Consultar', @contest.document.url, target: '_blank'
\|
= link_to 'Back', contests_path