config/routes.rb
Rails.application.routes.draw do
  resources :contracts

  resources :contests

   get '/cssslider', to: 'app/front#cssslider', as: :app_cssslider
   get '/atencion', to: 'app/front#atencion', as: :app_atencion
   get '/colocacioninstrumentos', to: 'app/front#colocacioninstrumentos', as: :app_colocacioninstrumentos
   get '/index', to: 'app/front#index', as: :app_index
   get '/estructuracion', to: 'app/front#estructuracion', as: :app_estructuracion
   get '/quienessomos', to: 'app/front#quienessomos', as: :app_quienessomos
   get '/juridica', to: 'app/front#juridica', as: :app_juridica
   get '/emisor', to: 'app/front#emisor', as: :app_emisor
   get '/ventajas', to: 'app/front#ventajas', as: :app_ventajas
   get '/contacto', to: 'app/front#contacto', as: :app_contacto
   get '/colocacion', to: 'app/front#colocacion', as: :app_colocacion
   get '/tarifas', to: 'app/front#tarifas', as: :app_tarifas
   get '/persona', to: 'app/front#persona', as: :app_persona
   get '/marcolegal', to: 'app/front#marcolegal', as: :app_marcolegal
   get '/concurso', to: 'contests#concurso'
   get '/contrataciones', to: 'contracts#contrataciones'
   get '/new', to: 'contests#new'
   get '/contrataciones', to: 'app/front#contrataciones', as: :app_contrataciones
   get '/mercadosecundario', to: 'app/front#mercadosecundario', as: :app_mercadosecundario
   get '/custodia', to: 'app/front#custodia', as: :app_custodia
   get '/estadisticas', to: 'app/front#estadisticas', as: :app_estadisticas
   get '/aplicacion', to: 'app/front#aplicacion', as: :app_aplicacion
   get '/calculadora', to: 'app/front#calculadora', as: :app_calculadora
   get '/admin/chart/un_chart/:id', to: 'admin/charts#un_chart', as: :un_chart
   get '/estadisticas/chart_front/:id', to: 'app/front#chart_front', as: :chart_front
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :charts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :banners do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :indicators do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :customizes do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/install_default', action: 'install_default'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
end

app/models/chart.rb
# Chart Model
class Chart < ActiveRecord::Base
  include ActivityHistory
  include CloneRecord
  mount_uploader :file, AttachmentUploader

  validates_presence_of :file, :name, :value_one

  # Fields for the search form in the navbar
  def self.search_field
    :name_or_file_cont
  end
end

app/models/helpers/charts_helper.rb
module ChartsHelper
  def un_chart(chart)
    graph = Chart.find(chart)
    line_chart un_chart_path, library: {
        title: {text: "#{graph.name}", x: -20},
        yAxis: {
            title: {
                text: 'Datos'
            }
        },
        xAxis: {
            type: 'datetime',
            title: {
                text: 'Datos'
            }
        },
        navigator: {
            enabled: true,
            adaptToUpdatedData: true,
            type: "datatime",
            series: {
                data: un_chart_path
            }
        },
    }
  end
end

app/controllers/admin/charts_controller.rb
module Admin
  # ChartsController
  class ChartsController < AdminController
    before_action :set_chart, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]
    require 'csv'
    require 'json'

    # GET /charts
    def index
      @q = Chart.ransack(params[:q])
      charts = @q.result(distinct: true)
      @objects = charts.page(@current_page)
      @total = charts.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to charts_path(page: @current_page.to_i.pred, search: @query)
      end
      @charts = Chart.all
      respond_to do |format|
        format.html
        format.xls { send_data(@charts.to_xls) }
      end
    end

    # GET /charts/1
    def show
    end

    # GET /charts/new
    def new
      @chart = Chart.new
    end

    # GET /charts/1/edit
    def edit
    end

    # POST /charts
    def create
      @chart = Chart.new(chart_params)

      if @chart.save
        redirect(@chart, params)
      else
        render :new
      end
    end

    # PATCH/PUT /charts/1
    def update
      if @chart.update(chart_params)
        redirect(@chart, params)
      else
        render :edit
      end
    end

    def clone
      @chart = Chart.clone_record params[:chart_id]

      if @chart.save
        redirect_to admin_charts_path
      else
        render :new
      end
    end

    # DELETE /charts/1
    def destroy
      @chart.destroy
      redirect_to admin_charts_path, notice: actions_messages(@chart)
    end

    def destroy_multiple
      Chart.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_charts_path(page: @current_page, search: @query),
        notice: actions_messages(Chart.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chart_params
      params.require(:chart).permit(:name, :file, :value_one, :value_two)
    end

    def show_history
      get_history(Chart)
    end
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
  def convert_to_amcharts_json(data_array)
    graph = Chart.find(data_array)
    @data = []
    options = { col_sep: '|', converters: :numeric, headers: true }
    CSV.foreach(graph.file.path, options) do |row|
      filename = "#{row['date,market1,market2'].downcase}.json"
      @data << JSON.pretty_generate(row.to_hash)
    end
    byebug
    @data.to_json.gsub(/\"text\"/, "text").html_safe
  end


  def prueba(id)
    @graph = Chart.find(id)
    data = File.open("#{@graph.file.path}").read
    @result = CSV.parse(data)
    @datos = @result.shift
    @result = @result.to_json.gsub(/\"text\"/, "text").html_safe
    respond_to do |format|
      format.html
      format.json { render :json => @users }
    end
  end

  def un_chart(chart)
    graph = Chart.find(chart)
    line_chart un_chart_path, width: "930px", height: "500px",  colors: ["#f45b5b", "#90ee7e"], library: {
        # chart: {
        #     type: 'spline'
        # },
        title: {
            text: "#{graph.name}"
        },
        # subtitle: {
        #     text: 'Irregular time data in Highcharts JS'
        # },
        navigator: {
            enabled: true,
            backgroundColor: "#90ee7e"
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: {
                month: '%e. %b',
                year: '%b'
            },
            title: {
                text: 'Fechas'
            }
        },
        yAxis: {
            title: {
                text: 'Bolsa'
            }
        }
        # tooltip: {
        #     headerFormat: '<b>{series.name}</b><br>',
        #     pointFormat: '{point.x:%e. %b}: {point.y:.2f} m'
        # },
        #
        # plotOptions: {
        #     line: {
        #         marker: {
        #             enabled: true
        #         }
        #     }
        # },

        # series: [{
        #     name: 'Winter 2007-2008',
        #
        #     data: un_chart_path
        # }]
    }
  end
  def chart_front(chart)
    graph = Chart.find(chart)
    line_chart chart_front_path(chart), width: "600px", height: "500px",  colors: ["#f45b5b", "#90ee7e"], library: {
        # chart: {
        #     type: 'spline'
        # },
        title: {
            text: "#{graph.name}"
        },
        # subtitle: {
        #     text: 'Irregular time data in Highcharts JS'
        # },
        navigator: {
            enabled: true,
            backgroundColor: "#90ee7e"
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: {
                month: '%e. %b',
                year: '%b'
            },
            title: {
                text: 'Fechas'
            }
        },
        yAxis: {
            title: {
                text: 'Bolsa'
            }
        }
        # tooltip: {
        #     headerFormat: '<b>{series.name}</b><br>',
        #     pointFormat: '{point.x:%e. %b}: {point.y:.2f} m'
        # },
        #
        # plotOptions: {
        #     line: {
        #         marker: {
        #             enabled: true
        #         }
        #     }
        # },

        # series: [{
        #     name: 'Winter 2007-2008',
        #
        #     data: un_chart_path
        # }]
    }
  end
end

app/views/admin/charts/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class('md-light')
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: 'height: {{windowHeight}}px;' }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t('keppler.titles.history')
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }

app/views/admin/charts/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_charts_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @chart] do |f|
						.row
							= f.input :name, label: "Nombre"
							= f.input :file, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
							= f.input :value_one, label: "Nombre del primer valor (Ej: Precio Venta)"
							= f.input :value_two, label: "Nombre del segundo valor (Ej: Precio Compra)"

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: '_save'
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'

app/views/admin/charts/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Chart
			= link_to edit_admin_chart_path(@chart), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%center.color-title= @chart.name.to_s.humanize
		%table.bordered
			%tbody
				%tr
					%th
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
					%td
						.display-value.fs-body-1.tc-black-2= @chart.id
				%tr
					%th
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.name")
					%td
						.display-value.fs-body-1.tc-black-2= @chart.name.blank? ? '----------' : @chart.name
				%tr
					%th
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.file")
					%td
						.display-value.fs-body-1.tc-black-2= @chart.file.blank? ? '----------' : @chart.file
		%table.bordered
			%tbody
				%td
					%center
						= link_to t('keppler.actions.back_history'), admin_charts_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/charts/_listing.html.haml
%tr{ id: "row-#{chart.id}" }
	- if can? :destroy_multiple, Chart
		%td.center.item-check
			= link_to '', admin_chart_path(chart), remote: true, class: 'show-row'
			%input{ type:'checkbox', class: 'filled-in', id: "checkbox-#{chart.id}", 'checklist-model'=>'check', 'checklist-value'=>"#{chart.id}", 'ng-click'=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{chart.id}" }

	%td.center
		= link_to '', admin_chart_path(chart, search: @query), remote: true, class: 'show-row'
		%span
			= chart.name
	%td.center
		= link_to '', admin_chart_path(chart, search: @query), remote: true, class: 'show-row'
		%span
			= chart.file.to_s.split("/").last
	%td.center.btn-w5
		= link_to admin_chart_path(chart), class: 'btn-floating waves-effect btn-flat', "data-no-turbolink" => true, "data-toggle" => 'tooltip', "data-placement" => 'bottom', title: 'Ver gráficas' do
			= material_icon.md_24.remove_red_eye.css_class('md-dark')
	- if can? :update, Chart
		%td.center.btn-w5
			= link_to edit_admin_chart_path(chart), class: 'btn-floating btn-flat', "data-toggle" => 'tooltip', "data-placement" => 'bottom', title: 'Editar' do
				= material_icon.md_18.create.css_class('md-dark')
	- if can? :clone, Chart
		%td.center.btn-w5
			= link_to admin_chart_clone_path(chart), class: 'btn-floating waves-effect btn-flat', "data-toggle" => 'tooltip', "data-placement" => 'bottom', title: 'Clonar' do
				= material_icon.md_24.content_copy.css_class('md-dark')
	- if can? :delete, Chart
		%td.center.btn-w5{style:'padding-right: 20px'}
			= link_to admin_chart_path(chart), class: 'btn-floating btn-flat', "data-toggle" => 'tooltip', "data-placement" => 'bottom', title: 'Borrar', method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
				= material_icon.md_18.delete.css_class('md-dark')

app/views/admin/charts/edit.html.haml
= title(t('keppler.titles.edit', model: "Charts"))
= render 'form'

app/views/admin/charts/index.html.haml
= title(t('keppler.titles.index', model: "Charts"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_chart_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only", "data-toggle" => 'tooltip', "data-placement" => 'bottom', title: 'New' do
			= material_icon.md_24.add
	= entries(@total, @objects)
	= link_to admin_charts_path(:format => :xls), class: "btn-tool-right btn-floating btn-flat right", "data-toggle" => 'tooltip', "data-placement" => 'bottom', title: 'Exportar a Excel' do
		= material_icon.md_18.save.css_class("md-dark")
	%table.bordered
		%tbody
			- unless @objects.blank?
				%tr{style:"background: #fff;"}
					%th{style: 'padding-left: 20px'}
					%th.center Nombre
					%th.center{style:"width: 50%;"} Archivo
					%th{ colspan: 4}
			- @objects.each do |chart|
				= render 'listing', chart: chart
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.charts"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_chart_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/charts/new.html.haml
= title(t('keppler.titles.new', model: "Charts"))
= render 'form'

app/views/admin/charts/show.html.haml
/%script{:src => "https://code.highcharts.com/stock/highstock.js"}
-# %link{:href => "https://www.amcharts.com/lib/3/plugins/export/export.css", :media => "all", :rel => "stylesheet", :type => "text/css"}/
-# %script{:src => "http://www.amcharts.com/lib/3/plugins/export/export.min.js"}
%script{:src => "/assets/js/amcharts.js", :type => "text/javascript"}
%script{:src => "/assets/js/serial.js", :type => "text/javascript"}
%script{:src => "/assets/js/papaparse.js"}
= title(t('keppler.titles.show', model: "Charts"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Chart
				= link_to admin_chart_path(@chart), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Chart
				= link_to edit_admin_chart_path(@chart), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_charts_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%center.color-title= @chart.name.to_s.humanize
				%table.bordered
					%tbody
						%tr
							%th
								.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
							%td
								.display-value.fs-body-1.tc-black-2= @chart.id.to_s.humanize
						%tr
							%th
								.display-label Nombre
							%td
								.display-value.fs-body-1.tc-black-2= @chart.name.blank? ? '----------' : @chart.name
						%tr
							%th
								.display-label Archivo
							%td
								.display-value.fs-body-1.tc-black-2= @chart.file.blank? ? '----------' : @chart.file.to_s.split("/").last
			#chartdiv{:style => "width: 920px; height: 400px;"}
:javascript
	var rowSupremo = []
	var chart;
	var chartData = [];
	var chartCursor;
	var primer_valor = "#{@chart.value_one}"
	var segundo_valor = "#{@chart.value_two}"
	console.log(primer_valor)

	AmCharts.ready(function() {
		// SERIAL CHART
		chart = new AmCharts.AmSerialChart();
		chart.pathToImages = "/documents/";
		chart.dataProvider = chartData;
		chart.categoryField = "date";
		chart.dataDateFormat = "DD/MM/YYYY";
		// listen for "dataUpdated" event (fired when chart is rendered) and call zoomChart method when it happens
		chart.addListener("dataUpdated", zoomChart);
		// AXES
		// category
		var categoryAxis = chart.categoryAxis;
		categoryAxis.parseDates = true; // as our data is date-based, we set parseDates to true
		categoryAxis.minPeriod = "DD"; // our data is daily, so we set minPeriod to DD
		categoryAxis.dashLength = 1;
		categoryAxis.gridAlpha = 0.15;
		categoryAxis.minorGridEnabled = true;
		categoryAxis.axisColor = "#DADADA";

		// value
		var valueAxis = new AmCharts.ValueAxis();
		valueAxis.axisAlpha = 0.2;
		valueAxis.dashLength = 1;
		chart.addValueAxis(valueAxis);

		// GRAPH
		var graph = new AmCharts.AmGraph();
		graph.title = "Blue Line";
		graph.valueField = "venta";
		graph.bullet = "round";
		graph.bulletBorderColor = "#FFFFFF";
		graph.bulletBorderThickness = 2;
		graph.bulletBorderAlpha = 1;
		graph.lineThickness = 2;
		graph.lineColor = "#b5030d";
		graph.negativeLineColor = "#0352b5";
		graph.balloonText = `[[category]]<br><b><span style='font-size:14px;'>${segundo_valor}: [[value]]</span></b`;
		graph.hideBulletsCount = 50; // this makes the chart to hide bullets when there are more than 50 series in selection
		// console.log(graph);
		chart.addGraph(graph);

		var graph = new AmCharts.AmGraph();
		graph.title = "red line";
		graph.valueField = "compra";
		graph.bullet = "round";
		graph.bulletBorderColor = "#FFFFFF";
		graph.bulletBorderThickness = 2;
		graph.bulletBorderAlpha = 1;
		graph.lineThickness = 2;
		graph.lineColor = "rgb(32, 172, 212)";
		graph.negativeLineColor = "#0352b5";
		graph.balloonText = `[[category]]<br><b><span style='font-size:14px;'>${primer_valor}: [[value]]</span></b`;
		graph.hideBulletsCount = 50; // this makes the chart to hide bullets when there are more than 50 series in selection
		// console.log(graph);
		chart.addGraph(graph);

		// CURSOR
		chartCursor = new AmCharts.ChartCursor();
		chartCursor.cursorPosition = "mouse";
		chart.addChartCursor(chartCursor);

		// SCROLLBAR
		var chartScrollbar = new AmCharts.ChartScrollbar();
		chartScrollbar.graph = graph;
		chartScrollbar.scrollbarHeight = 40;
		chartScrollbar.color = "#FFFFFF";
		chartScrollbar.autoGridCount = true;
		chart.addChartScrollbar(chartScrollbar);

		// WRITE
		chart.write("chartdiv");

		parseCSV("#{@chart.file}");
	});


	function parseCSV(data) {

		Papa.parse("#{@chart.file}", {
			download: true,
			step: function(row, parser) {
				var snowden = row.data;
				// console.log(snowden);
				llenarArray(snowden);
			},
			complete: function(results, file) {
				console.log("Parsing complete:", results, file);
				rowSupremo.reverse().shift();
				console.log(rowSupremo);
				if (rowSupremo[0][0].length==3){llenarChart(rowSupremo);}
				else if (rowSupremo[0][0].length==2){llenarChartUno(rowSupremo);}
				else{console.log("CHART INVALIDO");}

			}
		});

		function llenarArray(data){
			rowSupremo.push(data);
		}

		function llenarChart(data){
			for (var i = 0; i < data.length; i++) {
				rowSupremo[i][0][1] = rowSupremo[i][0][1].replace(/,/g, '.');
				rowSupremo[i][0][2] = rowSupremo[i][0][2].replace(/,/g, '.');
				var date = rowSupremo[i][0][0];
				var value = rowSupremo[i][0][1];
				var value2 = rowSupremo[i][0][2];
				var dataObject = {
					date: date,
					compra: value,
					venta: value2
				};
				// add object to chartData array
				chartData.push(dataObject);
				// console.log(dataObject);
			}
			chart.validateData();
		}

		function llenarChartUno(data){
			for (var i = 0; i < data.length; i++) {

				rowSupremo[i][0][1] = rowSupremo[i][0][1].replace(/,/g, '.');

				for (let a=0; a<= rowSupremo[i][0][1].length; a++){
					if (rowSupremo[i][0][1][a] == "."){
						rowSupremo[i][0][1] = rowSupremo[i][0][1].split(".").join("");
					}
				}

				var date = rowSupremo[i][0][0];
				var value = rowSupremo[i][0][1];
				var dataObject = {
					date: date,
					compra: value,
				};
				// add object to chartData array
				chartData.push(dataObject);
				// console.log(dataObject);
			}
			chart.validateData();
		}

	}

	// this method is called when chart is first inited as we listen for "dataUpdated" event
	function zoomChart() {
	// different zoom methods can be used - zoomToIndexes, zoomToDates, zoomToCategoryValues
	chart.zoomToIndexes(chartData.length - 40, chartData.length - 1);
	}

	// changes cursor mode from pan to select
	function setPanSelect() {
	if (document.getElementById("rb1").checked) {
	chartCursor.pan = false;
	chartCursor.zoomable = true;

	} else {
	chartCursor.pan = true;
	}
	chart.validateNow();
	}


:scss
	th{width:20%;}

app/views/admin/charts/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@chart.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");